version: '3.8'

services:
    mysql:
        image: mysql:8.0
        container_name: fex-mysql-server
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: 'toor'
            MYSQL_ROOT_HOST: '%'
            TZ: Asia/Bangkok

        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - mysql-network
        ports:
            - '3306:3306'
            

networks:
    mysql-network:

volumes:
    mysql-data:
